-- Hostinger MySQL schema for BrajMart
-- Create database first (example): CREATE DATABASE brajmart CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(40) DEFAULT '',
  role ENUM('user','admin') NOT NULL DEFAULT 'user',
  status ENUM('active','blocked') NOT NULL DEFAULT 'active',
  google_id VARCHAR(255) NULL,
  avatar VARCHAR(1024) DEFAULT '',
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  verification_token VARCHAR(255) NULL,
  verification_token_expires DATETIME NULL,
  addresses JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT 'Admin',
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  status ENUM('active','blocked') NOT NULL DEFAULT 'active',
  last_login DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  icon VARCHAR(255) NOT NULL,
  color VARCHAR(50) NOT NULL DEFAULT '#f59e0b',
  product_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2) NULL,
  image VARCHAR(1024) NOT NULL,
  category VARCHAR(255) NOT NULL,
  rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  review_count INT NOT NULL DEFAULT 0,
  badge VARCHAR(50) NULL,
  tags JSON NULL,
  in_stock TINYINT(1) NOT NULL DEFAULT 1,
  sold_count INT NOT NULL DEFAULT 0,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS carts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL UNIQUE,
  items JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  items JSON NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  status ENUM('confirmed','processing','shipped','out_for_delivery','delivered','cancelled') NOT NULL DEFAULT 'confirmed',
  customer_name VARCHAR(255) NULL,
  customer_email VARCHAR(255) NULL,
  shipping_address JSON NOT NULL,
  billing_address JSON NOT NULL,
  payment_method VARCHAR(100) NOT NULL,
  tracking_id VARCHAR(64) NULL,
  estimated_delivery DATETIME NULL,
  status_history JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_orders_user_id (user_id),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Start order IDs from 10000 (optional, matches previous Mongo counter style)
ALTER TABLE orders AUTO_INCREMENT = 10000;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NULL,
  customer_name VARCHAR(255) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  method VARCHAR(100) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status ENUM('paid','pending','failed','refunded') NOT NULL DEFAULT 'pending',
  transaction_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_payments_order (order_id),
  INDEX idx_payments_txn (transaction_id),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_status (
  token VARCHAR(255) PRIMARY KEY,
  status ENUM('paid','pending','failed') NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  amount DECIMAL(10,2) NULL,
  method VARCHAR(100) NULL,
  payment_id VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_payment_status_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  store_name VARCHAR(255) NOT NULL DEFAULT 'BrajMart',
  tagline VARCHAR(255) NOT NULL DEFAULT 'From Braj, With Love',
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  free_shipping_threshold DECIMAL(10,2) NOT NULL DEFAULT 499,
  shipping_fee DECIMAL(10,2) NOT NULL DEFAULT 49,
  store_email VARCHAR(255) NOT NULL DEFAULT 'support@brajmart.com',
  store_phone VARCHAR(50) NOT NULL DEFAULT '+91 9876543210',
  store_address VARCHAR(255) NOT NULL DEFAULT 'Vrindavan, Mathura, UP 281121, India',
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  min_order_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  max_order_quantity INT NOT NULL DEFAULT 10,
  delivery_eta_min_days INT NOT NULL DEFAULT 3,
  delivery_eta_max_days INT NOT NULL DEFAULT 7,
  cod_enabled TINYINT(1) NOT NULL DEFAULT 1,
  upi_enabled TINYINT(1) NOT NULL DEFAULT 1,
  card_enabled TINYINT(1) NOT NULL DEFAULT 1,
  maintenance_mode TINYINT(1) NOT NULL DEFAULT 0,
  meta_title VARCHAR(255) NOT NULL DEFAULT 'BrajMart - Authentic Vrindavan Products',
  meta_description TEXT NULL,
  store_logo VARCHAR(1024) NOT NULL DEFAULT '',
  favicon VARCHAR(1024) NOT NULL DEFAULT '',
  upi_id VARCHAR(255) NOT NULL DEFAULT '',
  upi_payee_name VARCHAR(255) NOT NULL DEFAULT 'BrajMart',
  social_links JSON NULL,
  announcement_bar JSON NULL,
  notifications JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
