export type ExportColumn<T> = {
  header: string;
  value: (row: T, index: number) => unknown;
};

type ExportOptions<T> = {
  title: string;
  fileName: string;
  rows: T[];
  columns: ExportColumn<T>[];
  format: 'excel';
};

const textValue = (value: unknown) => {
  if (value === null || value === undefined) return '';
  if (value instanceof Date) return value.toLocaleString('en-IN');
  if (Array.isArray(value)) return value.map(textValue).filter(Boolean).join(', ');
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
};

const escapeHtml = (value: unknown) =>
  textValue(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const safeFileName = (value: string, extension: string) => {
  const base = String(value || 'brajmart-export')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '')
    .slice(0, 80) || 'brajmart-export';
  return `${base}.${extension}`;
};

const downloadBlob = (content: string, mimeType: string, fileName: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
};

const tableHtml = <T,>(options: Omit<ExportOptions<T>, 'format'>) => {
  const generatedAt = new Date().toLocaleString('en-IN');
  const headers = options.columns.map((column) => `<th>${escapeHtml(column.header)}</th>`).join('');
  const rows = options.rows.map((row, rowIndex) => (
    `<tr>${options.columns.map((column) => `<td>${escapeHtml(column.value(row, rowIndex))}</td>`).join('')}</tr>`
  )).join('');

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(options.title)}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #111827; margin: 24px; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    .meta { color: #4b5563; font-size: 12px; margin-bottom: 18px; }
    table { border-collapse: collapse; width: 100%; font-size: 11px; }
    th { background: #f3f4f6; color: #111827; text-align: left; }
    th, td { border: 1px solid #d1d5db; padding: 7px; vertical-align: top; }
    tr:nth-child(even) td { background: #fafafa; }
  </style>
</head>
<body>
  <h1>${escapeHtml(options.title)}</h1>
  <div class="meta">Generated by BrajMart Admin on ${escapeHtml(generatedAt)}. Total rows: ${options.rows.length}</div>
  <table>
    <thead><tr>${headers}</tr></thead>
    <tbody>${rows}</tbody>
  </table>
</body>
</html>`;
};

const downloadExcel = <T,>(options: Omit<ExportOptions<T>, 'format'>) => {
  const worksheet = tableHtml(options);
  downloadBlob(
    worksheet,
    'application/vnd.ms-excel;charset=utf-8',
    safeFileName(options.fileName, 'xls')
  );
};

export const exportAdminData = <T,>(options: ExportOptions<T>) => {
  const normalized = {
    title: options.title,
    fileName: options.fileName,
    rows: options.rows,
    columns: options.columns,
  };

  downloadExcel(normalized);
  return true;
};
